export const initialTodos = [
  {
    id: 1,
    title: "Finalize the project report",
    description: "Review the final draft, check for errors, and add the conclusion section.",
    date: "2025-09-28",
    category: "Work",
    priority: "High",
    completed: false,
  },
  {
    id: 2,
    title: "Submit the design mockups",
    description: "Export all mockups as PNGs and upload them to the shared drive.",
    date: "2025-09-26",
    category: "Design",
    priority: "High",
    completed: true,
  },
  {
    id: 3,
    title: "Grocery shopping for the week",
    description: "Need to buy milk, bread, eggs, and vegetables for the upcoming week.",
    date: "2025-09-28",
    category: "Home",
    priority: "Medium",
    completed: false,
  },
  {
    id: 4,
    title: "Prepare for the team meeting",
    description: "Go over the talking points and prepare the slides for the presentation.",
    date: "2025-09-30",
    category: "Work",
    priority: "Medium",
    completed: false,
  },
  {
    id: 5,
    title: "Book flight tickets for vacation",
    description: "Find the best deals for round-trip tickets to Paris for December.",
    date: "2025-10-05",
    category: "Personal",
    priority: "High",
    completed: false,
  },
  {
    id: 6,
    title: "Pay the electricity bill",
    description: "The bill is due by the end of the month. Pay online via the portal.",
    date: "2025-09-27",
    category: "Finance",
    priority: "High",
    completed: true,
  },
];